[package]
org = "fixit"
name = "backend"
version = "0.1.0"
distribution = "2201.8.5"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.10.7"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.9.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.7.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.4.0"

[[dependency]]
org = "ballerinax"
name = "firebase.firestore"
version = "1.0.0"
