[package]
org = "fixit"
name = "backend"
version = "0.1.0"
distribution = "2201.12.4"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.9.3"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.8.1"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.6.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.3.0"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.11.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.8.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.0.0"
