# Firebase Firestore Configuration
# Replace these values with your actual Firebase project credentials

projectId = "your-firebase-project-id"
privateKeyId = "your-private-key-id"
privateKey = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY_HERE\n-----END PRIVATE KEY-----\n"
clientEmail = "your-service-account@your-project.iam.gserviceaccount.com"
clientId = "your-client-id"

# Server Configuration
[http]
port = 8080
host = "localhost"

# Development Settings
[dev]
enableCors = true
logLevel = "INFO"
