name: fixit
description: "FixIt - Service Offering System"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  provider: ^6.1.5
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.3
  location: ^8.0.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  flutter_polyline_points: ^2.1.0
  google_maps_flutter_android: ^2.16.2
  google_maps_flutter_ios: ^2.15.4
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - .env

  # Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#000000"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#006FFD"

  android_12:
    color: "#006FFD"
    image: "assets/images/logo.png"
